spring.application.name=webmusicai

# Kết nối SQL Server
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=MusicAI_DB;encrypt=true;trustServerCertificate=true;
spring.datasource.username=dtbmusic
spring.datasource.password=123456
spring.datasource.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver

# Cấu hình Hibernate JPA
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

# Gmail SMTP cấu hình gửi Email
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=tannguyenngoc05082000@gmail.com
spring.mail.password=vpdg moej vflz viue
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Cấu hình API Music
musicapi.key=d5ba87b7d8f5e0383bea4b61edd67442
musicapi.base-url=https://api.musicapi.ai